### PR TITLE
fix: race condition

### LINKED ISSUE #41: [Bug] Data Races detected in consensus/wbft with -race flag
#### System information

Gstable version: 0.1.0-stable
CL client & version: N/A (Unit Test)
OS & Version: OSX 15.5
Commit hash : adf7258804eb62861f31d59b6ea1afd6afde716e

#### Expected behaviour
'-race' option is enabled and tests are run, all tests must pass without any data race warnings.

#### Actual behaviour
During testing of the consensus pacakge, multiple WARNING: DATA RACE events occurred

#### Steps to reproduce the behaviour
```
go test -v -race github.com/ethereum/go-ethereum/consensus/...

```

Log File : [consensus_test-dev_conf1.20-exe1.22.log](https://github.com/user-attachments/files/24447002/consensus_test-dev_conf1.20-exe1.22.log)

### PR DESCRIPTION
**Pull request by colinkim**
refactor: fix data races in consensus core and timer management

- Add timerMu (sync.Mutex) to synchronize timer stop/set operations.
- Implement snapshotting for current Sequence and Round in timers to prevent races during view changes.
- Ensure thread-safety for futurePreprepareTimer in handlePreprepareMsg.
- Prevent potential deadlocks and nil pointer dereferences in callback routines.

These changes improve the stability of the consensus engine.

Close #41

### CODE REVIEW

File: consensus/wbft/core/roundstate.go [hunk 1]
```diff
@@ -113,8 +113,11 @@ func (s *roundState) SetRound(r *big.Int) {
 func (s *roundState) Round() *big.Int {
 	s.mu.RLock()
 	defer s.mu.RUnlock()
-
-	return s.round
+	if s.round == nil {
+		return nil
+	}
+	// Return a copy to avoid exposing internal mutable state after the lock is released.
+	return new(big.Int).Set(s.round)
```
Comment (eomti-wm) [inline consensus/wbft/core/roundstate.go]: 1. **Copy return is unnecessary**: `s.round` / `s.sequence` are never mutated directly — only replaced via `SetRound()` / `SetSequence()`. 
If immutability is a concern, `SetSequence()` should store a copy (`new(big.Int).Set(seq)`) like `SetRound()` already does, rather than copying on return.

2. **nil-check is unreachable**: both fields are always initialized in `newRoundState()`, and no code path sets them to `nil`.

**Suggestion**: revert to `return s.round` / `return s.sequence`, and fix `SetSequence()` to store a copy.

Comment (colinkim) [reply consensus/wbft/core/roundstate.go]: Thank you for your feedback. 
At the time, since SetRound()/SetSequence() were not actually being used, I decided to handle the defense on the getter side.
I added nil-checks and copy returns to Round()/Sequence() for two purposes:
(1) to defend against potential nil assignments in the future, and
(2) to prevent pointer aliasing with *big.Int.

However, as you pointed out, the nil-check is unlikely to be reached in practice.
I now judge that “returning the original value + explicitly stating read-only semantics” is simpler and clearer in intent than copy return.

Therefore, I will proceed as follows:
- Round()/Sequence() will revert to returning the original value as originally intended
- SetRound()/SetSequence() are unused (dead code) and potentially misused, modified to reflect your suggestion.
- Add a “read-only” annotation to the returned *big.Int in Round()/Sequence()

File: consensus/wbft/backend/engine_test.go [hunk 2]
```diff
@@ -52,10 +52,11 @@ import (
 	"github.com/ethereum/go-ethereum/triedb"
 )
 
-var blockEnqueueChannel chan *types.Block
+//var blockEnqueueChannel chan *types.Block
```
Comment (egonspace) [inline consensus/wbft/backend/engine_test.go]: How about just deleting this instead of leaving it?

Comment (colinkim) [reply consensus/wbft/backend/engine_test.go]: Thanks for catching this! I completely missed it. I've removed the line you pointed out, and I also took the opportunity to clean up some other leftover comments (like the inserter part) in the same function.

**Review by hominlee-wemade — APPROVED** [review]
